"""creacion_inicial_tablas

Revision ID: 5e8de8fcd4ae
Revises: 
Create Date: 2026-06-25 14:38:35.464515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8de8fcd4ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_username'), ['username'], unique=True)

    op.create_table('afiliados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('porcentaje_comision', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('whatsapp', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_afiliados_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_afiliados_email'), ['email'], unique=True)

    op.create_table('configuraciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=100), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('favicon_path', sa.String(length=300), nullable=True),
    sa.Column('color_primario', sa.String(length=7), nullable=True),
    sa.Column('color_secundario', sa.String(length=7), nullable=True),
    sa.Column('color_acento', sa.String(length=7), nullable=True),
    sa.Column('whatsapp_contacto', sa.String(length=500), nullable=True),
    sa.Column('mensaje_bienvenida', sa.String(length=255), nullable=True),
    sa.Column('mensaje_footer', sa.String(length=255), nullable=True),
    sa.Column('mensaje_copyright', sa.String(length=255), nullable=True),
    sa.Column('meta_descripcion', sa.Text(), nullable=True),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos_conocimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('contenido_texto', sa.Text(), nullable=False),
    sa.Column('vector_embedding', sa.JSON(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_proveedor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_oferta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('imagenes', sa.JSON(), nullable=True),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('imagenes_url', sa.JSON(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('stock_reservado', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)

    op.create_table('recordatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto_tarea', sa.String(length=500), nullable=False),
    sa.Column('fecha_hora_programada', sa.DateTime(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets_soporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('prioridad', sa.Enum('baja', 'media', 'alta', 'critica', name='prioridad_ticket'), nullable=False),
    sa.Column('estado', sa.Enum('abierto', 'en_progreso', 'resuelto', 'cerrado', name='estado_ticket'), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('contacto_nombre', sa.String(length=300), nullable=True),
    sa.Column('contacto_email', sa.String(length=400), nullable=True),
    sa.Column('escalado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.Column('resuelto_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transacciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('referencia_id', sa.String(length=50), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=20), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets_soporte.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('valor_estimado', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('etapa', sa.String(length=30), nullable=True),
    sa.Column('probabilidad', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('afiliado_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oportunidades_etapa'), ['etapa'], unique=False)

    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=100), nullable=False),
    sa.Column('cliente_telefono', sa.String(length=500), nullable=False),
    sa.Column('cliente_direccion', sa.Text(), nullable=False),
    sa.Column('productos_json', sa.JSON(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('afiliado_id', sa.Integer(), nullable=True),
    sa.Column('validado_por_vendedor', sa.Boolean(), nullable=True),
    sa.Column('validado_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('pagado_en', sa.DateTime(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.Column('pago_referencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliados.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pago_referencia')
    )
    op.create_table('reservas_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha_expiracion', sa.DateTime(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comisiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('afiliado_id', sa.Integer(), nullable=False),
    sa.Column('margen', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('pagada_en', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['afiliado_id'], ['afiliados.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=20), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva_porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('iva_monto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pedido_id')
    )
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_numero_factura'), ['numero_factura'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_numero_factura'))

    op.drop_table('facturas')
    op.drop_table('comisiones')
    op.drop_table('reservas_stock')
    op.drop_table('pedidos')
    with op.batch_alter_table('oportunidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oportunidades_etapa'))

    op.drop_table('oportunidades')
    op.drop_table('comentarios_tickets')
    op.drop_table('transacciones')
    op.drop_table('tickets_soporte')
    op.drop_table('recordatorios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))

    op.drop_table('productos')
    op.drop_table('documentos_conocimiento')
    op.drop_table('configuraciones')
    with op.batch_alter_table('afiliados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_afiliados_email'))
        batch_op.drop_index(batch_op.f('ix_afiliados_codigo'))

    op.drop_table('afiliados')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_username'))

    op.drop_table('admins')
    # ### end Alembic commands ###
